presubmits:
- always_run: true
  context: op1st/prow/pre-commit
  decorate: true
  name: pre-commit
  skip_report: false
  spec:
    containers:
    - command:
      - pre-commit
      - run
      - --all-files
      image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
- always_run: true
  context: op1st/prow/pytest
  decorate: true
  name: thoth-pytest-py38
  skip_report: false
  spec:
    containers:
    - command:
      - /bin/run-pytest
      image: quay.io/thoth-station/thoth-pytest-py38:v0.15.0
- always_run: true
  context: op1st/prow/mypy
  decorate: true
  name: thoth-mypy-py38
  skip_report: false
  spec:
    containers:
    - args:
      - .
      - --ignore-missing-imports
      - --config-file
      - mypy.ini
      command:
      - run-mypy
      image: quay.io/thoth-station/thoth-pytest-py38:v0.15.0
